# Generated by Django 4.2.6 on 2023-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memes", "0001_initial"),
        ("stickers", "0001_initial"),
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="memes",
            field=models.ManyToManyField(related_name="actors", to="memes.meme"),
        ),
        migrations.AddField(
            model_name="actor",
            name="stickers",
            field=models.ManyToManyField(related_name="actors", to="stickers.sticker"),
        ),
    ]
