# Generated by Django 4.2.6 on 2023-11-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0007_alter_actor_gender_alter_actor_memes_and_more"),
        ("content", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfavoritecontent",
            name="favorite_actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="library.actor",
                verbose_name="Любимые актеры",
            ),
        ),
        migrations.AlterField(
            model_name="userfavoritecontent",
            name="favorite_memes",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="content.meme",
                verbose_name="Любимые мемы",
            ),
        ),
        migrations.AlterField(
            model_name="userfavoritecontent",
            name="favorite_movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="library.movie",
                verbose_name="Любимые фильмы",
            ),
        ),
        migrations.AlterField(
            model_name="userfavoritecontent",
            name="favorite_stickers",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="content.sticker",
                verbose_name="Любимые стикеры",
            ),
        ),
        migrations.AlterField(
            model_name="userfavoritecontent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
