# Generated by Django 4.2.6 on 2023-10-07 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stickers", "0001_initial"),
        ("actors", "0002_actor_memes_actor_stickers"),
        ("memes", "0001_initial"),
        ("movies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_actors",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="actors.actor"
                    ),
                ),
                (
                    "favorite_memes",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="memes.meme"
                    ),
                ),
                (
                    "favorite_movies",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="movies.movie"
                    ),
                ),
                (
                    "favorite_stickers",
                    models.ManyToManyField(
                        blank=True, related_name="favorited_by", to="stickers.sticker"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
